"""Профиль исполнителя по умолчанию.

Совокупные возможности команды: Python-бэкенд + AI/ML + fullstack + DevOps.
Питает промпт LLM (семантический матч) и политику решения (жёсткие фильтры).
При необходимости приватности вынеси в файл по PROFILE_PATH и добавь в .gitignore.
"""

from app.domain.profile import ContractorProfile

DEFAULT_PROFILE = ContractorProfile(
    strong_skills=[
        "Python",
        "FastAPI",
        "Django",
        "PostgreSQL",
        "SQLAlchemy",
        "Redis",
        "REST API",
        "asyncio",
        "микросервисы",
        "RabbitMQ",
        "Celery",
        "Docker",
        "CI/CD",
        "Nginx",
        "Linux",
        "LLM",
        "LangChain",
        "RAG",
        "Telegram-боты",
        "автоматизация бизнес-процессов",
        "CRM-интеграции",
    ],
    working_skills=[
        # backend расширенно
        "Django REST Framework",
        "Litestar",
        "Flask",
        "Alembic",
        "Kafka",
        "Redpanda",
        "TaskIQ",
        # fullstack / frontend
        "React",
        "Next.js",
        "TypeScript",
        "Node.js",
        "JavaScript",
        "Bun",
        # AI / ML
        "PyTorch",
        "машинное обучение",
        "компьютерное зрение",
        "YOLO",
        "детекция объектов",
        "распознавание лиц",
        "NumPy",
        "Pandas",
        "Scikit-learn",
        "TensorFlow",
        "Milvus",
        "SBERT",
        "векторный поиск",
        "эмбеддинги",
        # DevOps расширенно
        "Docker Swarm",
        "Traefik",
        "Ansible",
        "Prometheus",
        "Grafana",
        "Loki",
        "GitHub Actions",
        "Jenkins",
        "S3",
        # автоматизация / скрапинг
        "веб-скрапинг",
        "Selenium",
        "Playwright",
        "requests",
        "httpx",
        "aiohttp",
    ],
    unsupported_skills=[
        "1C",
        "1С-Битрикс (разработка на CMS)",
        "PHP",
        "WordPress",
        "Tilda",
        "конструкторы сайтов",
        "iOS",
        "Android",
        "нативная мобильная разработка",
        "Java",
        "C#",
        "C++",
        "Unity",
        "геймдев",
    ],
    project_types=[
        "backend",
        "fullstack",
        "api",
        "devops",
        "machine_learning",
        "computer_vision",
        "llm",
        "rag",
        "automation",
        "data_processing",
        "web_scraping",
        "telegram_bots",
        "crm_integration",
    ],
    infrastructure_experience=[
        "Docker",
        "Docker Compose",
        "Docker Swarm",
        "Nginx",
        "Traefik",
        "GitHub Actions",
        "Jenkins",
        "Ansible",
        "Prometheus",
        "Grafana",
        "Loki",
        "Promtail",
        "Linux",
        "администрирование серверов",
        "CI/CD",
    ],
    integrations_experience=[
        "Telegram (боты и web-apps)",
        "Bitrix24",
        "AmoCRM",
        "Google Sheets API",
        "S3-совместимые хранилища",
        "LLM API (OpenAI, open-source)",
        "сторонние REST API",
        "CRM-системы",
    ],
    preferred_projects=[
        "Python backend (FastAPI / Django)",
        "REST API и микросервисы",
        "LLM-интеграции, чат-боты и AI-ассистенты",
        "RAG и семантический / векторный поиск",
        "Telegram-боты и Telegram web-apps",
        "автоматизация бизнес-процессов",
        "CRM-системы и интеграции (Bitrix24, AmoCRM)",
        "ML и компьютерное зрение (детекция, распознавание)",
        "DevOps, деплой и настройка серверов",
        "веб-скрапинг и сбор данных",
        "fullstack веб-сервисы (backend + React/Next.js)",
    ],
    rejected_projects=[
        "учебные работы (курсовые, дипломы, лабораторные за студента)",
        "помощь с домашними заданиями по программированию",
        "накрутка (подписчики, лайки, просмотры, отзывы)",
        "графический дизайн и отрисовка макетов",
        "простая вёрстка лендингов без логики",
        "сайты на конструкторах (Tilda, WordPress, Битрикс)",
        "SEO, копирайтинг и контент",
    ],
    minimum_budget=None,
    maximum_duration_months=None,
)
